---
# TODO: should re-enable this, once I figure out how to add k8s authentication at install time
#       currently canal-node container creates this on startup
# - name: Canal | Write Canal cni config
#   template:
#     src: "cni-canal.conflist.j2"
#     dest: "/etc/cni/net.d/10-canal.conflist"
#     owner: kube


- name: Canal | Create canal node manifests
  template:
    src: "{{item.file}}.j2"
    dest: "{{kube_config_dir}}/{{item.file}}"
  with_items:
    - {name: canal-crd, file: canal-crd.yaml, type: customresourcedefinition}
    - {name: canal-config, file: canal-config.yaml, type: cm}
    - {name: canal-node, file: canal-node.yaml, type: ds}
    - {name: canal, file: canal-node-sa.yml, type: sa}
    - {name: calico, file: canal-cr-calico.yml, type: clusterrole}
    - {name: flannel, file: canal-cr-flannel.yml, type: clusterrole}
    - {name: canal-calico, file: canal-crb-calico.yml, type: clusterrolebinding}
    - {name: canal-flannel, file: canal-crb-flannel.yml, type: clusterrolebinding}
  register: canal_manifests
  when:
    - inventory_hostname in groups['kube-master']

- name: Canal | Set cni directory permissions
  file:
    path: /opt/cni/bin
    state: directory
    owner: kube
    recurse: true
    mode: 0755

- name: Canal | Copy cni plugins
  unarchive:
    src: "{{ local_release_dir }}/cni-plugins-{{ image_arch }}-{{ cni_version }}.tgz"
    dest: "/opt/cni/bin"
    mode: 0755
    remote_src: yes

# TODO: currently canal-node container does this, but this should
#       be re-enabled to support cri-o
# TODO: Enabling this also means, that we have to write other config files
#       e.g. cnif conflist, flannel... etc... everything canal install-cni does now
# - name: Canal | Copy cni plugins from calico/cni
#   command: "{{ docker_bin_dir }}/docker run --rm -v /opt/cni/bin:/cnibindir {{ calico_cni_image_repo }}:{{ calico_cni_image_tag }} sh -c 'cp /opt/cni/bin/* /cnibindir/'"
#   register: cni_task_result
#   until: cni_task_result.rc == 0
#   retries: 4
#   delay: "{{ retry_stagger | random + 3 }}"
#   changed_when: false
#   tags:
#     - hyperkube
#     - upgrade

- name: Canal | Set cni directory permissions
  file:
    path: /opt/cni/bin
    state: directory
    owner: kube
    recurse: true
    mode: 0755

- name: Canal | Install calicoctl container script
  template:
    src: calicoctl-container.j2
    dest: "{{ bin_dir }}/calicoctl"
    mode: 0755
    owner: root
    group: root
  when:
    - inventory_hostname in groups['kube-master']

- name: Canal | Create network policy directory
  file:
    path: "{{ canal_policy_dir }}"
    state: directory
