---
- name: Ensure old versions of Docker are not installed. | Debian
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io
  when:
    - ansible_os_family == 'Debian'
    - (docker_versioned_pkg[docker_version | string] is search('docker-ce'))

- name: Ensure old versions of Docker are not installed. | RedHat
  package:
    name: '{{ item }}'
    state: absent
  # removed docker-selinux and docker-engine-selinux from that list,
  # as container-selinux is an alias and removing
  # docker-selinux removes container-selinux which removes docker itself as well
  loop: "{{ ['docker', 'docker-common', 'docker-engine',
             'docker-client', 'docker-client-latest',
             'docker-latest', 'docker-latest-logrotate',
             'docker-logrotate'] |
             union( docker_selinux_version is version('17.03', '>') |
                    ternary(['docker-ce-selinux'], [] )) }}"
  when:
    - ansible_os_family == 'RedHat'
    - (docker_versioned_pkg[docker_version | string] is search('docker-ce'))
    - not is_atomic
